config/routes.rb
Rails.application.routes.draw do
	mount Ckeditor::Engine => "/ckeditor"
	root to: "submissions#index"
	default_url_options host: "localhost"

	# Resources
	resources :submissions do
		resource :vote, only: %i[update]
		resources :comments do # currently only need create and destroy routes
			resource :vote, only: %i[update]
		end
		patch "add_watcher", on: :member
		patch "remove_watcher", on: :member
	end
	resources :categories, only: %i[show new create]

	# Sign up resource
	resources :logins, only: %i[new create]
	resources :account_activations, only: %i[edit]
	resources :password_resets, only: %i[new create edit update]

	# Named session control routes
	get "/login", to: "sessions#new"
	post "/login", to: "sessions#create"
	delete "/logout", to: "sessions#destroy"
end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController
	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		encrypt
		send_activation_email
	end

	private

	def encrypt
		@user.create_salt
		@user.encrypt_password
	end

	def send_activation_email
		@user.create_activation_digest
		if @user.save
			UserMailer.account_activation(@user).deliver_now
			flash[:sucess] = "Please check your email to activate your account."
			redirect_to root_url
		else
			flash[:notice] = @user.errors.full_messages.to_sentence 
			render :new
		end
	end

	def user_params
	 params.require(:user).permit(:username, :email, :password, :first_name, :last_name)
	end
end

app/helpers/logins_helper.rb
module LoginsHelper
	def gravatar_for(user)
		gravatar_id = Digest::MD5::hexdigest(user.email)
		gravatar_url = "https://secure.gravatar.com/avatar#{gravatar_id}"
		image_tag(gravatar_url, alt: user.first_name, class: "gravatar")
	end
end

app/views/logins/confirm_email.html.erb
<h1>Your Email is being confirmed</h1>

app/views/logins/edit.html.erb
<%if logged_in?%>
	<section class="hero">
		<h1>Editing User <%=@current_user.username%></h1>
	</section>
	<%= form_for(@current_user, url: {controller: 'logins', action: 'update'}, html: { class:"form" }) do |f|%>
		<% if @current_user.errors.any? %>
			<div id="error_explanation">
			<h2><%= pluralize(@current_user.errors.count, "error") %> prohibited this user from being saved:</h2>

			<ul>
			<% @current_user.errors.full_messages.each do |message| %>
				<li><%= message %></li>
			<% end %>
			</ul>
			</div>
		<% end %>
		<%= f.label :first_name%>
		<%= f.text_field :first_name%>

		<%= f.label :last_name%>
		<%= f.text_field :last_name%>
		
		<%= f.label :username %>
		<%= f.text_field :username %>

		<%= f.label :email %>
		<%= f.email_field :email %>

		<div class="form__actions">
        	<%= link_to "Cancel", root_path, class: "form__link" %>
        	<%= f.submit "Edit my", class: "button", name: "update" %>
    	</div>
	<%end%>
<%end%>

app/views/logins/new.html.erb
<section class="hero">
    <h1>Sign up</h1>
</section>

<%= form_for(:user, :url => {:controller => 'logins', :action => 'create'}, html: { class: "form" }) do |f| %>
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>

    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
    
    <%= f.label :username %>
    <%= f.text_field :username %>

    <%= f.label :email %>
    <%= f.email_field :email %>

    <%= f.label :password %>
    <%= f.password_field :password %>

    <%= f.label :password_confirmation, "Confirmation" %>
    <%= f.password_field :password_confirmation %>

    <div class="form__actions">
        <%= link_to "Cancel", root_path, class: "form__link" %>
        <%= f.submit "Create my account", class: "button" %>
    </div>
<% end %>

app/views/logins/show.html.erb
<%if logged_in?%>
	<section class="hero">
		<h1>Hi, <%=@current_user.first_name%></h1>
	</section>

	<div class="profile">
		<div class="profile__image">
			<div class="image">

			</div>
			<p> <%=@current_user.first_name%> <%=@current_user.last_name%></p><br>
			<%= image_tag "user-astronaut-solid.svg", alt: "Upvote", width: "150", height: "150" %><br>
			
			<%= link_to "Edit", edit_login_path(@current_user.id), class:"form__link"%>
		</div>

		<div class="profile__info">
		
			<p><b>First name:</b><br>	<%=@current_user.first_name%><br></p>
			<p><b>Last name:</b><br>	<%=@current_user.last_name%><br></p>
			<p><b>Username:</b><br>	<%=@current_user.username%><br></p>
			<p><b>Email:</b><br>	<%=@current_user.email%></p>
			<%submissions = Submission.where(user_id: @current_user.id)%>
			<% submissions.each do |submission| %>
				<% vote = Vote.find_by(post: submission, user_id: current_user.id) %>
				<%submission_class_id = ""%>
				<%if vote.nil?%>
					<%submission_class_id = "hasNotVoted"%>
				<%elsif vote.weight == 1%>
					<%submission_class_id = "hasVoted"%>
				<%else%>
					<%submission_class_id = "hasNotVoted"%>
				<%end%>
				<div class="index__submission <%=submission_class_id%>" id="submission">
					<div class="index__submission-vote-group">
						<div class="index__vote">
							<% if vote.nil? || vote.weight == 0 %> 
								<%= link_to submission_vote_path(submission_id: submission.id, user_id: current_user.id, weight: 1), method: :patch, class: "upvote", id: "upvote" do %>
									<%= image_tag "chevron_up-gray.svg", alt: "Upvote", width: "20", height: "20" %>
								<% end %>
							<% else %>
								<%= link_to submission_vote_path(submission_id: submission.id, user_id: current_user.id, weight: 0), method: :patch, class: "unvote", id: "unvote" do %>
									<%= image_tag "chevron_up-yellow.svg", alt:"Upvote", width: "20", height: "20" %>
								<%end%>
							<% end %>
							
							<br><p><%= submission.vote_count%></p>
						</div>
						<div class="index__contentStatusGroup">
							<div class="index__content" id="submission-content">
								<%= link_to submission do%>
									<h2><%= submission.title%></h2>
								<%end%>
							</div>
							<%status = submission.status.name%>
							<%if submission.status.name == "Open"%>
								<%status = "openTag"%>
							<%elsif submission.status.name == "Completed"%>
								<%status = "closedTag"%>
							<%else%>
								<%status = "rejectedTag"%>
							<%end%>
							<div class="index__tag index__statusTag <%=status%>" data-info = "<%= submission.status.name%>">
								<a href="#">
									<%= submission.status.name%>
								</a>
							</div>
						</div>
					</div>
					<div class = "index__tagGroup">
						<div class="index__tag color-<%=submission.category.color%>">
							<a href="<%=category_url(submission.category.id)%>">
							<%= submission.category.name.upcase%>
							</a>
						</div>
					</div>
				</div>
			<%end%>
		<div>
	</div>
<%else%>

<%end%>

app/views/logins/sucessful_login.html.erb
<h1>Login Sucessful<h1>