config/routes.rb
Rails.application.routes.draw do
	mount Ckeditor::Engine => "/ckeditor"
	root to: "submissions#index"
	default_url_options host: "localhost"

	# Resources
	resources :submissions do
		resource :vote, only: %i[update]
		resources :comments do # currently only need create and destroy routes
			resource :vote, only: %i[update]
		end
		patch "add_watcher", on: :member
		patch "remove_watcher", on: :member
	end
	resources :categories, only: %i[show new create]

	# Sign up resource
	resources :logins, only: %i[new create]
	resources :account_activations, only: %i[edit]
	resources :password_resets, only: %i[new create edit update]

	# Named session control routes
	get "/login", to: "sessions#new"
	post "/login", to: "sessions#create"
	delete "/logout", to: "sessions#destroy"
end

app/models/submission.rb
require "vote_helper.rb"
require "notification_helper.rb"

class Submission < ActiveRecord::Base
	include VoteHelper
	belongs_to :user
	belongs_to :category
	belongs_to :status
	has_many :votes
	has_many :comments
	has_many :post_changes
	has_and_belongs_to_many :watchers, class_name: "User", join_table: :watches

	validates :category_id, presence: true
	validates :user_id, presence: true
	validates :content, presence: true

	after_save :notify_users

	def self.status(statuses)
		self.where(status: Status.where(name: statuses))
	end

	def self.category(categories)
		self.where(category: Category.where(name: categories))
	end

	private

	def notify_users
		if vote_count_changed?
			post_change = PostChange.create(submission: self, post_change_type: "vote")
			NotificationHelper.notify_users(post_change)
		end

		return unless status_id_changed?
		post_change = PostChange.create(
			submission: self, post_change_type: "status",
			change_object: status
		)
		NotificationHelper.notify_users(post_change)
	end
end

app/controllers/submissions_controller.rb
class SubmissionsController < ApplicationController
	before_action :set_submission,
		only: %i[show edit update destroy add_watcher remove_watcher] #maybe use except intead of only since there are so many
	before_action :logged_in

	def logged_in
		return if logged_in?
		redirect_to login_url
	end

	def index
		@submissions = Submission.order(vote_count: :desc, created_at: :desc)
	end

	def show; end

	def new
		@submission = Submission.new
	end

	def edit; end

	def create
		@submission = Submission.new(submission_params)
		@submission.status_id = 1 #always sets the status to "open" on new submissions
		if @submission.save
			create_vote
			redirect_to @submission
			return
		end
		render :new
	end

	def update
		if @submission.update(submission_params)
			flash[:info] = "Submission was successfully updated."
			redirect_to @submission
		else
			flash[:info] = "Submission edit failed"
			render :edit
		end
	end

	def add_watcher
		@submission.watchers << User.find(params[:user_id]) #this should be the current_user esp since we already check for logged_in?
		@submission.save
		redirect_to :back
	end

	def remove_watcher
		@submission.watchers.delete(User.find(params[:user_id])) # ^^
		@submission.save
		redirect_to :back
	end

	def destroy
		@submission.destroy
		redirect_to submissions_url
	end

	private

	def submission_params
		sub = params.require(:submission).permit(:title, :content, :category_id, :status_id)
		sub.merge(user_id: current_user.id)
	end

	# Use callbacks to share common setup or constraints between actions.
	def set_submission
		@submission = Submission.find(params[:id])
	end

	def create_vote
		Vote.create(
			post: @submission, user_id: current_user.id,
			weight: 1
		)
	end
end

app/helpers/submissions_helper.rb
module SubmissionsHelper
	def self.sort(submissions, order)
		case order
		when "date newest to oldest"
			submissions.sort_by(&:created_at).reverse
		when "date oldest to newest"
			submissions.sort_by(&:created_at)
		when "votes low to high"
			submissions.sort_by(&:vote_count)
		else
			submissions.sort_by(&:vote_count).reverse
		end
	end

	def self.filter(submissions, filters)
		submissions = submissions.category(filters[:categories]) unless
			filters[:categories].nil?
		submissions = submissions.status(filters[:statuses]) unless
			filters[:statuses].nil?
		submissions
	end
end

app/views/submissions/_admin_status_tag.html.erb
<div class="tag">
	<%= form_for(@submission, html: { class: "form" }) do |f| %>
		<div class="field" id="select_for_show">
			<%=f.collection_select :status_id, Status.order(:name), :id, :name, {}, {onchange:"this.form.submit();", class:"tag__select"} %>
		</div>
	<%end%>	
</div>

app/views/submissions/_comment.html.erb
<br>
<!-- SUGGESTION: I think we should only allow users to delete their own comments, we could make a case for admins deleting comments as well -->
<!-- also used a decorator to remove some logic from this view -->
<div class="comment__header">
	<%= SubmissionDecorator.new(comment).comment_details(@submission, current_user) %>
</div>
<br>

<div class="comment__content">
	<div class="comment__vote">
		<div class="vote">
			<%= SubmissionDecorator.new(comment).comment_vote_link(@submission, current_user) %>
			<br><p><%= comment.vote_count %></p>
<!-- disabled because of issues getting multiple ckeditor instances	
		<a href="javascript:showReply('new_comment_<%=comment.id%>')"><i class="fas fa-comment-alt comment__icon"></i></a>	 
-->
		</div>
	</div>
	
	<div class="comment__text">
		<%= comment.content.html_safe %>
	</div>
</div>
<br>

app/views/submissions/_comments.html.erb
<% comments.each do |comment| %>
	<div class="comment">
		<%= render partial: "comment", locals: {comment: comment, parent_comment: parent_comment } %>
		<!-- Threaded comments disabled because of issues getting multiple ckeditor instances
		<div  id="new_comment_<%=comment.id%>">
			<%= render partial: 'new_comment', locals: { parent_comment: comment } %>
		</div>
		<% comment_children = Comment.where(parent_comment_id: comment.id) %>
		<% if comment_children.any? %>
			<br>	
			<%= render partial: "comments", locals: { comments: comment_children, parent_comment: comment }%>	
		<% end %>
		-->
	</div>
<% end %>

app/views/submissions/_form.html.erb
<%= form_for(@submission, html: { class: "form" }) do |f| %>
	<% if @submission.errors.any? %>
		<div id="error_explanation">
		<h2><%= pluralize(@submission.errors.count, "error") %> prohibited this submission from being saved:</h2>

		<ul>
		<% @submission.errors.full_messages.each do |message| %>
			<li><%= message %></li>
		<% end %>
		</ul>
		</div>
	<% end %>
	<div class="field">
		<%= f.label :categories %><br>
		<%= f.collection_select :category_id, Category.order(:name), :id, :name %>
	</div>
	<div class="field">
		<%= f.label :title %><br>
		<%= f.text_field :title %>
	</div>
	<div class="field">
		<%= f.label :content %><br>
		<%= javascript_include_tag Ckeditor.cdn_url %>
		<%= f.cktext_area :content, ckeditor: {toolbar: "mini"} %>
	</div>
	<div class="field">
		<%= f.label :user_id %><br>
		<%= f.text_field :user_id %>
	</div>
	<%if type == "new"%>
		<div class="form__actions">
			<%= link_to "Cancel", root_path, class: "form__link" %>
			<%= f.submit "Create Submission", class: "button" %>
		</div>
	<%elsif type == "update"%>
		<div class="form__actions">
			<%= link_to "Cancel", root_path, class: "form__link" %>
			<%= f.submit "Update Submission", class: "button", name: "update" %>
		</div>	
	<%end%>
<%end%>

app/views/submissions/_new_comment.html.erb
<% @comment = Comment.new %>
<%= form_for @comment, url: submission_comments_url(submission_id: @submission.id, parent_comment_id: parent_comment), html: {method: :post} do |f| %> 
		<%= f.cktext_area :content, ckeditor: {toolbar: "mini"} %>
		<%= f.submit "submit comment", class: "button comment-button" %>
<% end %>

app/views/submissions/_status_tag.html.erb
<% status = SubmissionDecorator.new(@submission).set_submission_status %>
<div class="index__tag index__statusTag <%=status%>" data-info = "<%= @submission.status.name%>">
    <a href="#">
        <%= @submission.status.name%>
    </a>
</div>

app/views/submissions/edit.html.erb
<section class="hero">
	<h1>Editing Submission</h1>
</section>
<%= form_for(@submission, html: { class: "form" }) do |f| %>
	<div class="field">
		<%=f.label :status%><br>
		<%=f.collection_select :status_id, Status.order(:name), :id, :name, class:"selector" %>
	</div>
	<% if @submission.errors.any? %>
		<div id="error_explanation">
			<h2><%= pluralize(@submission.errors.count, "error") %> prohibited this submission from being saved:</h2>

			<ul>
				<% @submission.errors.full_messages.each do |message| %>
					<li><%= message %></li>
				<% end %>
			</ul>
		</div>
	<% end %>
	<div class="field">
		<%= f.label :categories %><br>
		<%= f.collection_select :category_id, Category.order(:name), :id, :name, class:"selctor" %>
	</div>
	<div class="field">
		<%= f.label :title %><br>
		<%= f.text_field :title %>
	</div>
	<div class="field">
		<%= f.label :content %><br>
		<%= javascript_include_tag Ckeditor.cdn_url %>
		<%= f.cktext_area :content, ckeditor: {toolbar: "mini"} %>
	</div>
	<div class="field">
		<%= f.label :user_id %><br>
		<%= f.text_field :user_id %>
	</div>
	<div class="form__actions">
		<%= link_to "Cancel", root_path, class: "form__link" %>
		<%= f.submit "Update Submission", class: "button", name: "update" %>
	</div>	
<%end%>

app/views/submissions/index.html.erb
<div class="index">
	<div class="dropdown">
		<span class="dropbtn">All Categories <%= image_tag "chevron_up.svg", class: "header__logo", alt: "Dropdown icon", width: "15", height: "15" %></span>
		<hr>
		<div class="dropdown-content">
			<% Category.all.each do |category| %>
				<a href="<%= category_url(category.id)%>"><%=category.name%></a>
			<% end %>
		</div>
	</div>

	<div>
	<% @submissions.each do |submission| %>
		<% submission_class_id = SubmissionDecorator.new(submission).set_submission_class_id(current_user) %>
		<div class="index__submission <%=submission_class_id%>" id="submission">
			<div class="index__submission-vote-group">
				<div class="index__vote">
					<%= SubmissionDecorator.new(submission).display_vote_link(current_user, true) %>
					<br><p><%= submission.vote_count%></p>
				</div>
				<div class="index__contentStatusGroup">
					<div class="index__content" id="submission-content">
						<%= link_to submission do%>
							<h2><%= submission.title%></h2>
						<%end%>
					</div>
					<% status = SubmissionDecorator.new(submission).set_submission_status %>
					<div class="index__tag index__statusTag <%=status%>" data-info = "<%= submission.status.name%>">
						<a href="#">
							<%= submission.status.name%>
						</a>
					</div>
				</div>
			</div>
			<div class = "index__tagGroup">
				<div class="index__tag color-<%=submission.category.color%>">
					<a href="<%=category_url(submission.category.id)%>">
					<%= submission.category.name.upcase%>
					</a>
				</div>
			</div>
		</div>
	<% end %>
</div>	
<div class="form__actions">
	<form action="<%=new_submission_url%>">
		<input type="submit" value="New Submission" class="button" />
	</form>
</div>

app/views/submissions/new.html.erb
<section class="hero">
    <h1>New Submission</h1>
</section>
<%= javascript_include_tag Ckeditor.cdn_url %>
<%= form_for(@submission, html: { class: "form" }) do |f| %>
	<% if @submission.errors.any? %>
		<div id="error_explanation">
		<h2><%= pluralize(@submission.errors.count, "error") %> prohibited this submission from being saved:</h2>

		<ul>
		<% @submission.errors.full_messages.each do |message| %>
			<li><%= message %></li>
		<% end %>
		</ul>
		</div>
	<% end %>
	<div class="field">
		<%= f.label :categories %><br>
		<%= f.collection_select :category_id, Category.order(:name), :id, :name %>
	</div>
	<div class="field">
		<%= f.label :title %><br>
		<%= f.text_field :title %>
	</div>
	<% @submission.user_id = current_user.id%> <!-- hidden_tag field?, not sure what this is for since we merge on current_user info in submission_params method of controller -->
	<div class="field">
		<%= f.label :content %><br>
		<%= f.cktext_area :content, ckeditor: {toolbar: "mini"}%>
	</div>
    <div class="form__actions">
        <%= link_to "Cancel", root_path, class: "form__link" %>
        <%= f.submit "Create Submission", class: "button" %>
    </div>
<%end%>

app/views/submissions/new.js.erb
$('.upvote').bind('ajax:success', function(){
    alert("upvoted");
    location.reload();
    console.log();
})
$('.unvote').bind('ajax:success', function(){
    alert("unvoted");
    location.reload();
})

app/views/submissions/oldstuff.html.erb
		# <select name="menu1" id="menu1">
			# <% category=Category.all%>
			# <% category.each do |category| %>
			# 	<option value="<%=category_url(category.id)%>" selected= "All Categories">
			# 		<%=category.name%>
			# 	</option>
			# <%end%>
		# 	<option selected="selected"> All Categories </option>
		# </select>
		# <script type="text/javascript">
		# 	var urlmenu = document.getElementById( 'menu1' );
		# 	urlmenu.onchange = function() {
		# 		window.location.replace(  this.options[ this.selectedIndex ].value );
		# 	};
		# </script>

app/views/submissions/show.html.erb
<!--the page reloads whenever we vote. Suggestion: would be cool to reload with ajax -->
<div class = "show index">
	<div class = "show__dropdownVoteGroup">
		<div class = "show__voteTitleGroup">
			<div class="vote">
				<%= SubmissionDecorator.new(@submission).display_vote_link(current_user) %>
				<br><p><%= @submission.vote_count%></p>
			</div>
			<div class = "show__titleStatusUser">
				<h1><%=@submission.title%></h1>
				<div class = "show__status">
					<h3>Status:</h3>
					<% if current_user.admin? %>
						<%= render partial: "admin_status_tag" %>
					<% else %>
						<%= render partial: "status_tag" %>
					<% end %>
				</div>
				
				<% poster = @submission.user.username rescue "The fourth founder" %> 
				<h3>Submitted By: <%=poster%></h3>
			</div>
		</div>
		<div class = "dropdown">
			<span class="dropbtn"> <%= image_tag "ellipsis.svg", class: "header__logo", alt: "Menu", width: "15", length: "15"%></span>
			<div class = "dropdown-content">
				<%= link_to "Delete", @submission, method: :delete, data: { confirm: 'Are you sure?' }, class:"form__link" %>
				<%= link_to "Back", submissions_path, class:"form__link"%>
				<%= link_to "Edit", edit_submission_path(@submission), class: "form__link"%>
				<% if @submission.watchers.include? current_user %>
					<%= link_to "Unwatch", remove_watcher_submission_path(submission_id: @submission.id, user_id: current_user.id), method: :patch %>
				<% else %>
					<%= link_to "Watch", add_watcher_submission_path(submission_id: @submission.id, user_id: current_user.id), method: :patch %>
				<% end %>
			</div>	
		</div>
	</div>
	<div class = "show__content">
	<h2 class = "contentHeader"> Content </h2><hr>
		<%=@submission.content.html_safe%>
	</div>
	<div class = "show__comments">
		<%= javascript_include_tag Ckeditor.cdn_url %>
		<%= render partial: "new_comment", locals: {parent_comment: nil} %>
		<% comments = @submission.comments.order(vote_count: :desc, created_at: :desc).where(parent_comment: nil) %>
		<%= render partial: "comments", locals: {comments: comments, parent_comment: nil} %> 
	</div>
</div>