config/routes.rb
Rails.application.routes.draw do
	mount Ckeditor::Engine => "/ckeditor"
	root to: "submissions#index"
	default_url_options host: "localhost"

	# Resources
	resources :submissions do
		resource :vote, only: %i[update]
		resources :comments do # currently only need create and destroy routes
			resource :vote, only: %i[update]
		end
		patch "add_watcher", on: :member
		patch "remove_watcher", on: :member
	end
	resources :categories, only: %i[show new create]

	# Sign up resource
	resources :logins, only: %i[new create]
	resources :account_activations, only: %i[edit]
	resources :password_resets, only: %i[new create edit update]

	# Named session control routes
	get "/login", to: "sessions#new"
	post "/login", to: "sessions#create"
	delete "/logout", to: "sessions#destroy"
end

app/views/layouts/_header.html.erb
<header class="header">
	<div class="contain header__contain">
		<%= link_to root_path, class: "header__title" do %>
			<%= image_tag "logo.svg", class: "header__logo", alt: "Flywheel logo", width: "50", height: "50" %>
			<h1>Flydeas</h1>
		<% end %>

		<ul class="header__nav">
			<% if logged_in? %>
				<li><%= link_to "Log out #{@current_user.first_name}", logout_path, method: :delete %></li>
				<li><%= link_to "Profile", login_path(@current_user.id)%> <%= image_tag "user-astronaut-solid.svg", alt: "Upvote", width: "20", height: "20" %><br></li>
			<% else %>
				<li><%= link_to "Log in", loginApp_path %> </li>
				<li> <%= link_to "Sign up", new_login_path %></li>
			<% end %>
		</ul>
	</div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>Flydeas</title>
		<%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
		<link rel="stylesheet" type: "text/css" href="/fonts/museo_sans_rounded/museo_sans_rounded.css" media="all">
		<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.1/css/all.css" integrity="sha384-O8whS3fhG2OnA5Kas0Y9l3cfpmYjapjI0E4theH4iuMD+pLhbf6JI0jIMfYcK3yZ" crossorigin="anonymous">	
		<%= csrf_meta_tags %>
	</head>

	<body>
		<%= render "layouts/header" %>
		<% flash.each do |key, value| %>
			<div class="flash-message --<%= key %>">
				<div class="contain"><%= value %></div>
			</div>
		<% end %>
		<%= yield %>
		<% debug(params) if Rails.env.development? %>
		<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
	</body>
</html>